# cicd-test-deploy.yml

name: test-deploy

on:
  push:
    branches: [test-deploy]
    
permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
#     env:
#       working-directory: ./BE
      
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          distribution: "temurin"
          
      - name: Change wrapper permissions
        run: chmod +x gradlew
        shell: bash
        working-directory: ${{env.working-directory}}
        
      - name: Build with Gradle
        run: ./gradlew bootJar
        shell: bash
        working-directory: ${{env.working-directory}}
        
      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash
        working-directory: ${{ env.working-directory }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://${{ secrets.S3_BUCKET_NAME }}/$PROJECT_NAME/$GITHUB_SHA.zip
        working-directory: ${{env.working-directory}}
      
